Fix send_all on eio
issuu/ocaml-zmq pull request #132
Opened 2024-05-05 22:56 UTC by ComanderP

Was trying the bindings on eio and for some reason `Zmq_eio.Socket.send_all` wasn't working at all, but `Zmq_eio.Socket.send` was. Checked the source code and I suppose the wrong argument was given inside the function (do correct me if I'm wrong).
It finally works with the change locally built on my machine (at least I think so).

2024-05-07 12:10 UTC, andersfugmann requested changes
The messages argument is important, as the send_all should be fully completed (i.e. all messages sent) before continuing.

2024-05-07 12:10 UTC, andersfugmann commented on zmq-eio/src/socket.ml
> +  request t t.senders (fun () -> Zmq.Socket.send_all ~block:false t.socket)
```suggestion
let send_all t messages =
  request t t.senders (fun () -> Zmq.Socket.send_all ~block:false t.socket messsages)
```

2024-05-07 12:10 UTC, andersfugmann commented on zmq-eio/src/socket.ml
> +  request t t.senders (fun () -> Zmq.Socket.send_msg_all ~block:false t.socket)
```suggestion
let send_msg_all t messages =
  request t t.senders (fun () -> Zmq.Socket.send_msg_all ~block:false t.socket messsages)
```

2024-05-07 12:11 UTC, andersfugmann commented
That definitely seems like an error - but I think the fix is incomplete. Thanks for raising this!

The messages to be sent needs to happen as part of the function. I've added suggestions (althouhg I'm not sure they work as expected). Also I think the tests needed to be ameded to verify `send_all` and `recv_all`.

2024-05-07 17:56 UTC, ComanderP commented
I've added your suggestions to the pull request.
For the tests, I'm not sure if I'm the right person to do them 😅, but I can surely try if someone gives me some guidance.

2024-05-09 15:27 UTC, andersfugmann commented
Tests should be added to `eio_zmq/test/test.ml`. A simple test that verifies that send_all followed by a receive_all works as expected. Look at `test_send_receive`. However that test uses the `send` and `recv` functions defined in the test, which in terms calls `Zmq_eio.Socket.send`, so you will need to call `Zmq_eio.Socket.send_all` and ` Zmq_eio.Socket.recv_all` function directly.

2024-05-09 22:20 UTC, ComanderP commented
Done.
There was a repeated usage of the 1st send/receive test `test_send_receive` which I replaced with the new test (I assume that was a typo).

2024-05-10 06:55 UTC, andersfugmann commented
Looks good. Thanks for doing this. I'll merge once the CI tests passes

2024-05-19 07:43 UTC, merged

2024-05-19 07:43 UTC, andersfugmann commented
Thanks